### ISSUE TITLE
Crash in tcp-info at head on my machine:

### ISSUE THREAD

**Issue by pboothe** [m-lab/tcp-info#66]
First I ran:

```
$ docker build .
[... lots of output elided...]
Step 17/17 : ENTRYPOINT ["/bin/tcp-info"]
 ---> Running in 42bdb83ccac9
Removing intermediate container 42bdb83ccac9
 ---> a7d8c11395ac
Successfully built a7d8c11395ac
```

then I ran:

```
$ docker run --net=host a7d8c11395ac
2019/04/02 19:43:01 Prometheus metrics in tcp-info.metrics are registered.
2019/04/02 19:43:01 argsfromenv.go:38: Argument output=
2019/04/02 19:43:01 argsfromenv.go:38: Argument prom=:9090
2019/04/02 19:43:01 argsfromenv.go:38: Argument reps=0
2019/04/02 19:43:01 argsfromenv.go:38: Argument trace=false
2019/04/02 19:43:01 argsfromenv.go:38: Argument uuid-prefix-file=pboothe2.nyc.corp.google.com_1553784371_unsafe
2019/04/02 19:43:01 saver.go:252: Starting Saver
2019/04/02 19:43:01 saver.go:344: Cache info total 0  local 0 same 0 diff 0 new 0 err 0
2019/04/02 19:43:01 saver.go:215: Skipping &{10 5 3 0 {[237 228] [20 108] [38 32 0 0 16 3 4 22 41 31 26 35 250 152 217 73] [38 7 248 176 64 13 12 9 0 0 0 0 0 0 0 188] [0 0 0 0] [51 24 0 0 0 0 0 0]} 8316 0 0 0 0} 2019-04-02 19:43:01.772 +0000 UTC
2019/04/02 19:43:01 saver.go:215: Skipping &{10 5 3 0 {[165 186] [20 108] [38 32 0 0 16 3 4 22 41 31 26 35 250 152 217 73] [38 7 248 176 64 13 12 9 0 0 0 0 0 0 0 188] [0 0 0 0] [53 24 0 0 0 0 0 0]} 33556 0 0 0 0} 2019-04-02 19:43:01.772 +0000 UTC
2019/04/02 19:43:01 saver.go:215: Skipping &{10 5 3 0 {[237 230] [20 108] [38 32 0 0 16 3 4 22 41 31 26 35 250 152 217 73] [38 7 248 176 64 13 12 9 0 0 0 0 0 0 0 188] [0 0 0 0] [58 24 0 0 0 0 0 0]} 8316 0 0 0 0} 2019-04-02 19:43:01.772 +0000 UTC
2019/04/02 19:43:01 saver.go:215: Skipping &{10 5 3 0 {[156 56] [20 108] [38 32 0 0 16 3 4 22 41 31 26 35 250 152 217 73] [38 7 248 176 64 13 12 9 0 0 0 0 0 0 0 188] [0 0 0 0] [60 24 0 0 0 0 0 0]} 14524 0 0 0 0} 2019-04-02 19:43:01.772 +0000 UTC
panic: runtime error: index out of range

goroutine 41 [running]:
github.com/m-lab/tcp-info/netlink.(*ParsedMessage).Compare(0xc0002a7a40, 0xc00016fd10, 0x30, 0x1, 0x0)
	/go/src/github.com/m-lab/tcp-info/netlink/netlink.go:197 +0x471
github.com/m-lab/tcp-info/saver.(*Saver).swapAndQueue(0xc00012a100, 0xc0002a7a40)
	/go/src/github.com/m-lab/tcp-info/saver/saver.go:309 +0x205
github.com/m-lab/tcp-info/saver.(*Saver).MessageSaverLoop(0xc00012a100, 0xc000114420)
	/go/src/github.com/m-lab/tcp-info/saver/saver.go:264 +0xb0
created by main.main
	/go/src/github.com/m-lab/tcp-info/main.go:98 +0x1b8
```

Something in the netlink message is crashing.

**Comment by pboothe** [comment]
Fixed by #67
